import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import About from '../components/about'
import Cards from '../components/cards'
import FavoriteList from '../components/favoritelist'
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'
import Protected from './protected'
import SearchPage from './searchpage'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {/* 
      <Link href="/protected"><a>Protected</a></Link> */}

      <main className='bg-white/75 w-full h-screen ' >

        <SearchPage />
        <About />


      </main>




    </div>
  )
}
